config/routes.rb
NomaddressCom::Application.routes.draw do
  get "static_pages/error"

  resources :subscribers

  resources :subscriptions

  resources :users
  match "run_update" => "users#run_update"

  resources :addresses

  resource :user_sessions

  match "address_display" => "addresses#addressdisplay"

  match "about" => "application#about"

  match "faq" => "application#faq"
    
  match "privacy" => "application#privacy"

  match "contact" => "application#contact"

  match "login" => "user_sessions#new"

  match "logout" => "user_sessions#destroy"

  root :to => 'users#new'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :address
  belongs_to :subscriber
  belongs_to :subscribable, :polymorphic => true
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new(:address_id => params[:address_id])
    @dmv_subscribable = Dmv.find_or_initialize_by_address_id(params[:address_id])
    @amazon_subscribable = Amazon.find_or_initialize_by_address_id(params[:address_id])
    if params[:firsttime]
      render :firsttime
    else
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @subscription }
      end
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    if params[:firsttime]
      @subscription = Subscription.new(params[:subscription])

      @subscription.save
      respond_to do |format|
        format.html { redirect_to :controller => 'users', :action => 'new', :address_id => @subscription.address_id.to_s}
      end
    else
      if params[:dmv]
        @subscription = Subscription.create(:address_id => params[:dmv][:address_id])
        @dmv = Dmv.find_or_initialize_by_address_id(params[:dmv][:address_id])
        @dmv.update_attributes(params[:dmv])
        @dmv.subscription = @subscription
        @dmv.save
      end
      if params[:amazon]
        @subscription = Subscription.create(:address_id => params[:amazon][:address_id])
        @amazon = Amazon.find_or_initialize_by_address_id(params[:amazon][:address_id])
        @amazon.update_attributes(params[:amazon])
        @amazon.subscription = @subscription
        @amazon.save
      end
        
      redirect_to user_path(current_user)
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_amazon.html.erb
<div>
<b>  Email: </b>
<%= @subscribable.email %>
</div>
<div>
<b> Full Name: </b>
<%= @subscribable.full_name %>
</div>
<div>
<b> Country: </b>
<%= @subscribable.country %>
</div>
<div>
<b> Phone Number: </b>
<%= @subscribable.phone_number %>
</div>

app/views/subscriptions/_amazon_form.html.erb
<%= form_for(@amazon_subscribable, :url => {:controller => :subscriptions, :action => :create}, :method => :post) do |f| %>
  <%= f.hidden_field :address_id, :value => @amazon_subscribable.address_id %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Full Name" %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label "Phone number" %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/_dmv.html.erb
<div>
<b> Lincense #: </b>
<%= @subscribable.driver_license %>
</div>
<div>
<b> SSN: </b>
<%= @subscribable.ssn %>
</div>
<div>
<b> County: </b>
<%= @subscribable.county %>
</div>

app/views/subscriptions/_dmv_form.html.erb
<%= form_for(@dmv_subscribable, :url => {:controller => :subscriptions, :action => :create}, :method => :post) do |f| %>
  <%= f.hidden_field :address_id, :value => @dmv_subscribable.address_id %>
  <div class="field">
    <%= f.label :driver_license %><br />
    <%= f.text_field :driver_license%>
  </div>
  <div class="field">
    <%= f.label "Last 4 of SSN" %><br />
    <%= f.text_field :ssn%>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/_firstTimeForm.html.erb
<%= form_for(@subscription) do |f| %>
  <div class="subscribers">
    <% Subscriber.all.each do |sub| %>
      <%= render 'subscriber', :subscriber => sub %>
      <%= f.hidden_field :address_id, :value => @subscription.address_id %>
      <%= hidden_field :firsttime, "true"%>
    <% end %>
  </div>
  <div class="next_button">
    <%= f.submit "Next", :type => :image, :src => "/assets/next_button.png" %>
  </div>
<% end %>

app/views/subscriptions/_quickshow.html.erb
<div class="subscription">
  <% if @subscription.subscribable_id != nil %>
    <b>Subscriber:</b>
    <%= @subscription.subscribable_type %>
    <%= render "subscriptions/#{@subscription.subscribable_type.downcase}.html.erb", :@subscribable => @subscription.subscribable %>
  <% end %>
</div>

app/views/subscriptions/_subscriber.html.erb
<%= image_tag(subscriber.img_path, :size => '56x56', :class => 'subscriber_img', :id => subscriber.name) %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/firsttime.html.erb
<div class='threestep'>
  <h2>Who should we notify?</h2>

  <div class='form_box'>
    <h2 style="padding-top:10px">Subscribers:</h2>
    <%= render 'firstTimeForm' %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Subscriber</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.subscriber_id %></td>
    <td><%= subscription.address_id %></td>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<script>
	$(function() {
		$( "#accordion" ).accordion({ active: false, collapsible: true});
	});
	</script>

<h1>New subscription</h1>

<div id="accordion">
	<h3><a href="#">DMV</a></h3>
	<div>
                <%= render 'dmv_form' %>
	</div>
	<h3><a href="#">Amazon</a></h3>
	<div>
		<%= render 'amazon_form' %>
	</div>
</div>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subscriber:</b>
  <%= @subscription.subscribable_type %>
</p>

<p>
  <b>Address:</b>
  <%= @subscription.address.line1 %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |