config/routes.rb
NomaddressCom::Application.routes.draw do
  get "static_pages/error"

  resources :subscribers

  resources :subscriptions

  resources :users
  match "run_update" => "users#run_update"

  resources :addresses

  resource :user_sessions

  match "address_display" => "addresses#addressdisplay"

  match "about" => "application#about"

  match "faq" => "application#faq"
    
  match "privacy" => "application#privacy"

  match "contact" => "application#contact"

  match "login" => "user_sessions#new"

  match "logout" => "user_sessions#destroy"

  root :to => 'users#new'

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def addressdisplay
    render "addresses/address_display"
  end

  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])
    @user = current_user
    @user.addresses << @address
    respond_to do |format|
      if @address.save
        format.html { redirect_to user_path(@user)}
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<script>

  $(function() {
    $( ".next_button button:first" ).button({icons: { primary: null, secondary: "ui-icon-arrowthick-1-e" } }) });
  
</script>

<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="fields">
    <div class="field">
      <%= f.label "Street" %>
      <%= f.label "Apt #", :class => "apt_label" %><br />
      <%= f.text_field :line1 %>
      <%= f.text_field :line2, :class => "apt_text" %>
    </div>
    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_field :city, :style => "width: 60%;" %>
    </div>
    <div class="field">
      <%= f.label :state %>
      <%= f.label "Zip", :style => "padding-left: 148px;" %><br />
      <%= f.text_field :state, :style => "width: 120px;" %>
      <%= f.text_field :zip, :style => "margin-left: 50px; width: 60px;" %>
    </div>
    <div class="field">
      <%= f.select :category,options_for_select( Address.valid_categories )%>
    </div>
  </div>


  <div class="next_button">
    <button>Next</button>
  </div>

<% end %>

app/views/addresses/_quickshow.html.erb
<script type="text/javascript">
$(document).ready(function(){
$( "input:submit", ".update_button" ).button();
});
</script>

<% if @address %>
<p>
<div>
  <b>Line1:</b>
  <%= @address.line1 %>
</div>
<div>
<% if @address.line2 %>
    <b>Line2:</b>
    <%= @address.line2 %>
<% end %>
</div>
<div>
  <b>City:</b>
  <%= @address.city %>
</div>
<div>
  <b>State:</b>
  <%= @address.state %>
</div>
<div>
  <b>Zip:</b>
  <%= @address.zip %>
</div>
</p>

</br>
<div id="subscriptions">
  <h2> Subscribers </h2>
  <% @address.subscriptions.each do |sub| %>
    <%= render "subscriptions/quickshow.html.erb", :@subscription => sub %>
  <% end %>

  <% else %>
    You haven't updated any addresses for this category yet. Update today!
  <% end %>
</div>
<div style="text-align:center"> 
  <%= link_to "Create/Edit Subscriptions", new_subscription_path(:address_id => @address.id) %>
  Or
  <button id="update">Update</button>
</div>

<!-- For the popup dialog -->
<div id="dialog-form" title="We need your password to decrypt your secure information">

<script>
  $(function() {
    
    var password = $( "#password" ),
      allFields = $( [] ).add( password ),
      tips = $( ".validateTips" );

    function updateTips( t ) {
      tips
        .text( t )
        .addClass( "ui-state-highlight" );
      setTimeout(function() {
        tips.removeClass( "ui-state-highlight", 1500 );
      }, 500 );
    }

    function checkLength( o, n ) {
      if ( !o.val().length > 0 ) {
        o.addClass( "ui-state-error" );
        updateTips( "Password is required" );
        return false;
      } else {
        return true;
      }
    }

    $( "#dialog-form" ).dialog({
      autoOpen: false,
      height: 200,
      width: 350,
      modal: true,
      buttons: {
        "Update your Address!": function() {
          var bValid = true;
          allFields.removeClass( "ui-state-error" );

          bValid = bValid && checkLength( password, "password" );
          if ( bValid ) {
            $( '#passwordForm' ).submit();
            //$( this ).dialog( "close" );
          }
        },
        Cancel: function() {
          $( this ).dialog( "close" );
        }
      },
      close: function() {
        allFields.val( "" ).removeClass( "ui-state-error" );
      }
    });

    $( "#update" )
      .button()
      .click(function() {
        $( "#dialog-form" ).dialog( "open" );
      });
  });
  </script>
  <form id="passwordForm" action="/run_update" method="post" data-remote="true">
  <fieldset>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" autofocus="autofocus" required="required" />
    <input type="hidden" name="address_id" value="<%= @user.addresses.first.id %>"/>
  </fieldset>
  </form>
</div>

app/views/addresses/address_display.html.erb
<script>
	$(function() {
		$( "#accordion" ).accordion();
	});
</script>





<div id="accordion">
	<h3><a href="#">Home</a></h3>
	<div>
		<p>
			<img src="/assets/home_icon.png">My Home
		</p>
	</div>
	<h3><a href="#">Office</a></h3>
	<div>
		<p>
			My Office
		</p>
	</div>
	<h3><a href="#">School</a></h3>
	<div>
		<p>
			Unviersity of Illinois
		</p>
	</div>
	<h3><a href="#">Travel</a></h3>
	<div>
		<p>
			Somewhere
		</p>
	</div>
	<h3><a href="#">Vacation</a></h3>
	<div>
		<p>
			Somewhere
		</p>
	</div>
</div>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Line1</th>
    <th>Line2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.line1 %></td>
    <td><%= address.line2 %></td>
    <td><%= address.city %></td>
    <td><%= address.state %></td>
    <td><%= address.zip %></td>
    <td><%= address.type %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<div class='threestep'>
  <h2>Update your address, everywhere, in minutes</h2>

  <div class='form_box'>
    <%= render 'form' %>
  </div>
</div>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Line1:</b>
  <%= @address.line1 %>
</p>

<p>
  <b>Line2:</b>
  <%= @address.line2 %>
</p>

<p>
  <b>City:</b>
  <%= @address.city %>
</p>

<p>
  <b>State:</b>
  <%= @address.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @address.zip %>
</p>

<p>
  <b>Type:</b>
  <%= @address.type %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>