config/routes.rb
NomaddressCom::Application.routes.draw do
  get "static_pages/error"

  resources :subscribers

  resources :subscriptions

  resources :users
  match "run_update" => "users#run_update"

  resources :addresses

  resource :user_sessions

  match "address_display" => "addresses#addressdisplay"

  match "about" => "application#about"

  match "faq" => "application#faq"
    
  match "privacy" => "application#privacy"

  match "contact" => "application#contact"

  match "login" => "user_sessions#new"

  match "logout" => "user_sessions#destroy"

  root :to => 'users#new'

end

app/views/layouts/_footer.html.erb
<%= link_to 'About', about_path %> |
<%= link_to 'FAQ', faq_path %> |
<%= link_to 'Privacy', privacy_path %> |
<%= link_to 'Contact us', contact_path %>
<br>
<%= link_to (image_tag "fb_logo.png", {:size=> "30x30"}), "http://facebook.com", {:class => "img_link", :target => "_blank"} %>
<%= link_to (image_tag "twitter_logo.png", {:size=> "30x30"}), "http://twitter.com", {:class =>"img_link", :target => "_blank"} %>
<%= link_to (image_tag "reddit_logo.png", {:size=> "30x30"}), "http://reddit.com", {:class => "img_link", :target => "_blank"} %>
<br>
Copyright 2012 Nomaddress.com

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NomAddress <%=@title || ""%></title>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" %>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class= 'header'>
    <%- link = current_user ? user_path(current_user) : root_path -%>
    <a href=<%= link %> class="img_link"><img src='/assets/chopped-logo.png'/></a>
    <div style="float:right;padding-right:10px">
      <% if current_user %>
        <%= "Hey #{current_user.first_name}!  " %>
        <%= link_to 'Logout', logout_path %>
      <% else %>
         <%= link_to 'Login', login_path %>
      <% end %>
    </div>
  </div>
	<div class = "clear"></div>
<div class="content">
<div class="push_header">
</div>
  <section>
    <%= yield %>
  </section>
<div class="push_footer"></div>
</div>
  <div class='footer'>
    <div class = "fword"><%= render 'layouts/footer' %></div>
  </div>
</body>
</html>